// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
// import { defineConfig } from "prisma/config";

// Prisma config - commented out due to module resolution issues
// Using default Prisma configuration from schema.prisma
export default {};
